default:
  http_metas:
    content-type: text/html

  metas:
    title:        Asterisell
    robots:       noindex, nofollow
    description:  Asterisell project
    keywords:     asterisell
    language:     en

  stylesheets:    [asterisell, appmenu_style, '/sf/sf_admin/css/main.css', '/css/tree_list.css']

  javascripts:    ['/js/jquery.js']

  has_layout:     true
  layout:         asterisell_layout
#  components:
#    headerInfo:   [login, user]


# all:
#  components:
#    headerInfo: [login, user]
