generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      ArParams
    theme:            default

    fields:
      name: { name: Name }

      service_name: { name: Website Name, help: "The name of the entity associated to this website interface. Also displayed as the website title." }

      service_provider_website: {name: "Website address", help: "The URL of the website." }

      service_provider_email: { name: Email }

      logo_image: { name: Logo image, help: "Logo / image to display in website interface." }

      logo_html_color: { name: Logo color, help: "Optional field. The primary color in HTML format (Hexadeciaml RGB), which can be used for customizing the look and feel of invoices, screens and reports. Note: Use Null for the default color." }

      slogan:  { name: Slogan, help: "Slogan / message displayed under the logo." }

      logo_image_in_invoices: { name: "Logo image inside invoices", help: "Logo / image to show on invoices. Usually a higher resolution image is required compared to the stndard website logo. The image will be scaled to a fixed width in the invoice templates to mantain it's aspect ratio. Note: For some images you will have to use an image with an empty space on the right side. Alpha channel (transparency) is not supported. If you wish to upload an image manually, it must be placed inside the web/images directory on the server." }

      footer: { name:  Footer text }
 
      user_message:         { name: User message, help: The welcome message displayed to customers / users after succesful login. }

      legal_name:           { name: Company name }

      vat:                  { name: VAT, help: VAT registration number }

      vat_tax_perc_as_php_decimal: { name: VAT %, type: input_tag, help: "The VAT % to apply on invoices. Example: '15.0' Note: The vlue should be entered without the '%' symbol and '.' should be used as a decimal separator." }

      legal_address:        { name: Address }

      legal_city:           { name: City }

      legal_zipcode:        { name: ZIP / Area code }

      legal_state_province: { name: Province / State, help: "This is not a required field and may be left empty." }

      legal_country:        { name: Country, help: "This is not a required field and may be left empty." }

      legal_email:          { name: email, help: "The email address to be displayed in the address header." }

      legal_website:        { name: Company website URL }

      legal_phone:          { name: Telephone 1, help: "The telephone number to be displayed in the address header." }

      phone2:               { name: Telephone 2 }

      invoice_notes:        { name: Invoice footer note, help: "Invoice footer note. These notes are placed before the customer specific notes as configured in Entities->Party TAGS. It may contain placeholders like ${pay_due_date}, ${pay_within_days}, ${invoice_number}.", type: textarea_tag, params: size=60x5 }

      invoice_payment_terms: { name: Invoice payment terms, help: "Invoice payment and other legal terms. It may be customized using Entities->Party TAGS.", type: textarea_tag, params: size=60x5 }

      invoice_payment_due_in_xx_days: { name: Invoice payment due days, help: "The payment due date to be used with supported invoice templates." }

      legal_fax:            { name: Fax, help: "The fax number to be displayed in the address header." }

      invoicing_email_address: { name: Email address }

      sender_name_on_invoicing_emails: { name: Sender name, help: "The name of the sender to be used in email messages. "}

      html_notes_on_the_login_form: { name: Notes to display on the login form, help: "HTML content to be displayed on the login form. ", type: textarea_tag, params: size=60x5 }

      official_calldate: { name: "Official call date", help: "Calls after this date can be freely re-rated before processing and closing the billing period since they are not included in the official billing report yet. Calls before this date can only be re-rated using explicit admin commands. Note: This parameter is automatically updated when billing reports are processed and confirmed. Only administrators can manually override this date." }

    list:
      title: Params
      actions: []
      display: [=name, service_name, service_provider_website]

    edit:
      title: Params
      actions:
        _save: ~

      fields:
        my_logo_image: { name: Logo image, help: "Logo / image to display in website interface. Upload logos / images using the 'Upload Files' module." }
        my_logo_image_in_invoices: { name: "Logo image inside invoices", help: "Logo image inside invoices", help: "Logo / image to show on invoices. Usually a higher resolution image is required compared to the stndard website logo. The image will be scaled to a fixed width in the invoice templates to mantain it's aspect ratio. Note: For some images you will have to use an image with an empty space on the right side. Alpha channel (transparency) is not supported. If you wish to upload an image manually, it must be placed inside the web/images directory on the server." }

      display:
        Params: [name, official_calldate]
        VoIP service information (used on website): [service_name, service_provider_website, service_provider_email, _my_logo_image, logo_html_color, slogan, footer, html_notes_on_the_login_form]
        Company legal information (used on invoices): [legal_name, vat, vat_tax_perc_as_php_decimal, legal_address, legal_city, legal_zipcode, legal_state_province, legal_country, legal_email, legal_website, legal_phone, phone2, legal_fax, invoice_notes, invoice_payment_terms, invoice_payment_due_in_xx_days, _my_logo_image_in_invoices]
        Parameters for emails, used for sending to customer invoices and/or reports: [invoicing_email_address, sender_name_on_invoicing_emails ]
