exportToFileSuccess:
  has_layout: false
  http_metas:
    cache-control: private
    pragma: private
    content-type: text/plan; charset=utf-8
    content-disposition: inline; filename="asterisell_errors.txt"
# NOTE:
#
# cache-control "private" and pragma "private" are needed
# as a workaround for bug
#
# http://support.microsoft.com/kb/323308/en-us

